languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Egor Howell"
# copyright = "Egor Howell"

[params]
  dateFormat = "2 January 2006"

  description = "Personal website of Egor Howell"

[params.author]
  name = "Egor Howell"
  image = "img/pic2.png"
  headline = "Data Scientist, Machine Learning Engineer & Content Creator"
  bio = "Data Scientist, Machine Learning Engineer & Content Creator."
  links = [
    { youtube = "https://youtube.com/@egorhowell" },
    { medium = "https://medium.com/@egorhowell" },
    { instagram = "https://instagram.com/egorhowell" },
    { github = "https://github.com/egorhowell" },
    { linkedin = "https://www.linkedin.com/in/egorhowell/" },
  ]